on:
  push:
    branches:
      - main

name: Semantic Release on merge

jobs:
  build:
    name: Build go file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16'
      - run: go build -o ./dist/msdcli-amd64 msdcli.go
      - name: Archive downloader artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binary-folder
          path: ./dist
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: build
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 13
      - name: Download build file
        uses: actions/download-artifact@v2
        with:
          name: binary-folder
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 16
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
            @semantic-release/release-notes-generator
            @semantic-release/commit-analyzer
            @semantic-release/exec
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
